package cadastroclientes;
import CadastroClientes.Cliente;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author andre
 */
public class OperacoesCliente extends javax.swing.JFrame {

    /**
     * Creates new form OperacoesCliente
     */
    public OperacoesCliente() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nomeInput = new javax.swing.JTextField();
        telefoneTitle = new javax.swing.JLabel();
        telefoneInput = new javax.swing.JTextField();
        emailTitle = new javax.swing.JLabel();
        emailInput = new javax.swing.JTextField();
        logradouroTitle = new javax.swing.JLabel();
        logradouroInput = new javax.swing.JTextField();
        numeroInput = new javax.swing.JTextField();
        numeroTitle = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        complementoInput = new javax.swing.JTextField();
        bairroTitle = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        bairroInput = new javax.swing.JTextField();
        cidadeTitle = new javax.swing.JLabel();
        cidadeInput = new javax.swing.JTextField();
        estadoTitle = new javax.swing.JLabel();
        cepTitle = new javax.swing.JLabel();
        cepInput = new javax.swing.JTextField();
        estadoInput = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Clientes");
        setLocationByPlatform(true);
        setName("operacoes"); // NOI18N
        setResizable(false);

        nomeTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomeTitle.setText("Nome");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Operações de cliente");

        nomeInput.setToolTipText("Nome do cliente");

        telefoneTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        telefoneTitle.setText("Telefone");

        telefoneInput.setToolTipText("Telefone do cliente");
        telefoneInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneInputActionPerformed(evt);
            }
        });

        emailTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        emailTitle.setText("E-mail");

        emailInput.setToolTipText("E-mail do cliente");
        emailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailInputActionPerformed(evt);
            }
        });

        logradouroTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        logradouroTitle.setText("Logradouro");

        logradouroInput.setToolTipText("Ruas, Avenidas, praças...");

        numeroTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        numeroTitle.setText("Numero");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Complemento");

        bairroTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bairroTitle.setText("Bairro");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cidadeTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cidadeTitle.setText("Cidade");

        estadoTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        estadoTitle.setText("Estado");

        cepTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cepTitle.setText("CEP");

        estadoInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logradouroTitle)
                            .addComponent(telefoneTitle)
                            .addComponent(emailTitle)
                            .addComponent(nomeTitle)
                            .addComponent(numeroTitle)
                            .addComponent(jLabel5)
                            .addComponent(bairroTitle)
                            .addComponent(cidadeTitle)
                            .addComponent(estadoTitle)
                            .addComponent(cepTitle))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(emailInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(telefoneInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(nomeInput, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logradouroInput, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numeroInput, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(complementoInput, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bairroInput, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cidadeInput, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel1))
                            .addComponent(cepInput, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estadoInput, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeTitle)
                    .addComponent(nomeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telefoneTitle)
                    .addComponent(telefoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailTitle)
                    .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logradouroTitle)
                    .addComponent(logradouroInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numeroTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(numeroInput, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(complementoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bairroTitle)
                    .addComponent(bairroInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cidadeTitle)
                    .addComponent(cidadeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadoTitle)
                    .addComponent(estadoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cepTitle)
                    .addComponent(cepInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telefoneInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneInputActionPerformed

    private void emailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailInputActionPerformed
    
    private void limparCampos() {
    nomeInput.setText("");
    telefoneInput.setText("");
    emailInput.setText("");
    logradouroInput.setText("");
    numeroInput.setText("");
    complementoInput.setText("");
    bairroInput.setText("");
    cidadeInput.setText("");
    estadoInput.setSelectedItem("AC");
    cepInput.setText("");
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(this, "Entrando na função");
        String nome = nomeInput.getText();
        String telefone = telefoneInput.getText();
        String email = emailInput.getText();
        String logradouro = logradouroInput.getText();
        String numero = numeroInput.getText();
        String complemento = complementoInput.getText();
        String bairro = bairroInput.getText();
        String cidade = cidadeInput.getText();
        String estado = estadoInput.getSelectedItem().toString();
        String cep = cepInput.getText();
        
            if (nome.isEmpty() || telefone.isEmpty() || email.isEmpty() || logradouro.isEmpty()
            || numero.isEmpty() || complemento.isEmpty() || bairro.isEmpty()
            || cidade.isEmpty() || estado.isEmpty() || cep.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Preencha todos os campos.");
        return;
    }
        
        Cliente cliente = new Cliente(nome, telefone,email,logradouro,numero,complemento,bairro,cidade,estado,cep);
        ClientesData data = new ClientesData();
        
        try{
        data.registrar(cliente);
        limparCampos();
        TabelaClientesGUI tabela = new TabelaClientesGUI();
        System.out.println(cliente.toString());
        tabela.atualizarTabela();
        JOptionPane.showMessageDialog(this, "Cliente Registrado com sucesso!");
        }
        catch(Exception e ){
            JOptionPane.showMessageDialog(this, "Ocorreu um erro ao salvar: "+e);
        }
        
        
        
  
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperacoesCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperacoesCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperacoesCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperacoesCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperacoesCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairroInput;
    private javax.swing.JLabel bairroTitle;
    private javax.swing.JTextField cepInput;
    private javax.swing.JLabel cepTitle;
    private javax.swing.JTextField cidadeInput;
    private javax.swing.JLabel cidadeTitle;
    private javax.swing.JTextField complementoInput;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel emailTitle;
    private javax.swing.JComboBox<String> estadoInput;
    private javax.swing.JLabel estadoTitle;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField logradouroInput;
    private javax.swing.JLabel logradouroTitle;
    private javax.swing.JTextField nomeInput;
    private javax.swing.JLabel nomeTitle;
    private javax.swing.JTextField numeroInput;
    private javax.swing.JLabel numeroTitle;
    private javax.swing.JTextField telefoneInput;
    private javax.swing.JLabel telefoneTitle;
    // End of variables declaration//GEN-END:variables
}
